# Generated by Django 4.2.28 on 2026-04-25 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Nova Commerce', max_length=120)),
                ('tagline', models.CharField(blank=True, max_length=180)),
                ('logo', models.ImageField(blank=True, upload_to='settings/')),
                ('favicon', models.ImageField(blank=True, upload_to='settings/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('whatsapp', models.CharField(blank=True, max_length=40)),
                ('address_en', models.CharField(blank=True, max_length=255)),
                ('address_ar', models.CharField(blank=True, max_length=255)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('homepage_title_en', models.CharField(default='Premium products, delivered beautifully', max_length=160)),
                ('homepage_title_ar', models.CharField(default='منتجات فاخرة تصل إليك بأناقة', max_length=160)),
                ('homepage_subtitle_en', models.TextField(default='A production-ready commerce experience for modern brands.')),
                ('homepage_subtitle_ar', models.TextField(default='تجربة تجارة إلكترونية جاهزة للعلامات التجارية الحديثة.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Store setting',
                'verbose_name_plural': 'Store settings',
            },
        ),
    ]
