# Generated by Django 5.0.6 on 2026-04-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storesetting',
            name='site_name',
            field=models.CharField(default='Cosmos Commerce', max_length=120),
        ),
    ]
