# Generated by Django 4.2.28 on 2026-04-25 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=180)),
                ('title_ar', models.CharField(blank=True, max_length=180)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('excerpt_en', models.CharField(blank=True, max_length=255)),
                ('excerpt_ar', models.CharField(blank=True, max_length=255)),
                ('body_en', models.TextField()),
                ('body_ar', models.TextField(blank=True)),
                ('cover', models.ImageField(blank=True, upload_to='blog/')),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('meta_title', models.CharField(blank=True, max_length=160)),
                ('meta_description', models.CharField(blank=True, max_length=255)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
