# Generated by Django 4.2.28 on 2026-07-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='features_ar',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='name_ar',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='tagline_ar',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
