# Generated by Django 5.0.6 on 2026-04-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='is_360_view',
            field=models.BooleanField(default=False),
        ),
    ]
