# Generated by Django 5.0.6 on 2026-04-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productimage_is_360_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='products/videos/'),
        ),
    ]
