# Generated by Django 4.2.28 on 2026-05-01 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productimage_image_url_alter_productimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='image_url',
        ),
    ]
