# Generated by Django 4.2.28 on 2026-07-24 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0005_remove_productimage_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='The store manager responsible for this product.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_products', to=settings.AUTH_USER_MODEL),
        ),
    ]
